"""Generates every Soviet Presidium inlay file from presidium_data.py.

Run:  python gen_presidium.py
Writes into the mod folder two levels up (this file lives in <mod>/_tools/presidium/).
Set MOD_ROOT to override.
"""
import os, re, struct, zlib
from pathlib import Path
from presidium_data import *

MOD = Path(os.environ.get("MOD_ROOT") or Path(__file__).resolve().parents[2])
HDR = "# GENERATED by _tools/presidium/gen_presidium.py - edit presidium_data.py instead\n"
BLANK = "GFX_SOV_pres_blank"

CID = {c["key"]: i + 1 for i, c in enumerate(CHARACTERS)}
FID = {f[0]: i + 1 for i, f in enumerate(FACTIONS)}
MID = {m[0]: i + 1 for i, m in enumerate(MINISTRIES)}
MIN = {m[0]: m for m in MINISTRIES}
CH = {c["key"]: c for c in CHARACTERS}
SLOTS = range(1, MAX_SEATS + 1)

# ---- validation
for c in CHARACTERS:
    assert c["faction"] in FID, f"{c['key']}: unknown faction {c['faction']}"
    for t in c["traits"]:
        assert t in TRAITS, f"{c['key']}: unknown trait {t}"
for m, h in START_SEATS:
    assert m in MID and (h is None or h in CID), f"START_SEATS: bad entry {m}, {h}"
assert len(START_SEATS) <= MAX_SEATS and LAYOUT_BREAKS[-1] == MAX_SEATS


def write(rel, data, bom=False):
    p = MOD / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(data, bytes):
        p.write_bytes(data)
    else:
        p.write_text(data, encoding="utf-8-sig" if bom else "utf-8")
    print("wrote", rel)


def cv(var, val):
    return f"check_variable = {{ {var} = {val} }}"


# ============================================================ layouts
W, LEFT_W, TOP, GRID_H, TEXT_H = 1000, 175, 45, 560, 54
GRID_W = W - LEFT_W - 5


def best_layout(n):
    best = None
    for cols in range(2, 8):
        rows = -(-n // cols)
        cell_w = GRID_W // cols
        s = min(0.65, (GRID_H / rows - TEXT_H - 6) / 210, (cell_w - 10) / 156)
        if cell_w >= 130 and (best is None or s > best[2]):
            best = (cols, rows, s, cell_w)
    return best


LAYOUTS = []  # (index, lo, hi, cols, rows, scale, cell_w)
lo = 0
for i, hi in enumerate(LAYOUT_BREAKS, 1):
    cols, rows, s, cw = best_layout(hi)
    LAYOUTS.append((i, lo, hi, cols, rows, s, cw))
    lo = hi
H = max(TOP + L[4] * (int(210 * L[5]) + TEXT_H + 6) for L in LAYOUTS) + 10


def slot_shown(L, i):
    lo, hi = L[1], L[2]
    return f"check_variable = {{ SOV_pres_seat_min^num > {max(lo, i - 1)} }} check_variable = {{ SOV_pres_seat_min^num < {hi + 1} }}"


# ============================================================ blank sprite (8x8 transparent tga)
write("gfx/interface/SOV_pres_blank.tga",
      struct.pack("<BBBHHBHHHHBB", 0, 0, 2, 0, 0, 0, 0, 0, 8, 8, 32, 8) + bytes(8 * 8 * 4))
write("interface/SOV_Stalin_presidium.gfx", HDR + f"""spriteTypes = {{
	spriteType = {{
		name = "{BLANK}"
		texturefile = "gfx/interface/SOV_pres_blank.tga"
	}}
}}
""")

# ============================================================ .gui
def text(name, x, y, w, ctx, font="hoi_16mbs"):
    return f"""		instantTextBoxType = {{
			name = "{name}"
			position = {{ x = {x} y = {y} }}
			font = "{font}"
			context_aware_text = {ctx}
			maxWidth = {w}
			maxHeight = 18
			fixedsize = yes
			format = center
			alwaystransparent = yes
		}}
"""


def icon(name, x, y, sc, tt):
    return f"""		iconType = {{
			name = "{name}"
			spriteType = "{BLANK}"
			position = {{ x = {x} y = {y} }}
			scale = {sc:.2f}
			context_aware_tooltip = {tt}
		}}
"""


gui = [HDR, f"""guiTypes = {{
	containerWindowType = {{
		name = "SOV_presidium_inlay_window"
		position = {{ x = 0 y = 0 }}
		size = {{ width = {W} height = {H} }}
		clipping = no
		background = {{ name = "background" quadTextureSprite = "GFX_tiled_window_transparent" }}
"""]
gui.append(text("SOV_pres_title", 0, 10, W, "[SOV_pres_title_text]", "hoi_20bs"))
gui.append(icon("SOV_pres_leader_portrait", 33, 60, 0.7, "[SOV_pres_leader_tt]"))
gui.append(text("SOV_pres_leader_name", 0, 212, LEFT_W, "[SOV_pres_leader_name]", "hoi_18mbs"))
gui.append(text("SOV_pres_leader_title", 0, 232, LEFT_W, "[SOV_pres_leader_title]"))
for L in LAYOUTS:
    li, _, hi, cols, rows, s, cw = L
    row_h = int(210 * s) + TEXT_H + 6
    for i in range(1, hi + 1):
        cx, cy = LEFT_W + ((i - 1) % cols) * cw, TOP + ((i - 1) // cols) * row_h
        py = cy + int(210 * s) + 2
        n = f"SOV_pres_L{li}_s{i}"
        gui.append(icon(f"{n}_portrait", cx + (cw - int(156 * s)) // 2, cy, s, f"[{n}_tt]"))
        gui.append(text(f"{n}_name", cx, py, cw - 4, f"[{n}_name]"))
        gui.append(text(f"{n}_title", cx, py + 16, cw - 4, f"[{n}_title]"))
        gui.append(text(f"{n}_faction", cx, py + 32, cw - 4, f"[{n}_faction]"))
gui.append("\t}\n}\n")
write("interface/SOV_Stalin_presidium_inlay.gui", "".join(gui))

# ============================================================ inlay window
def portrait_list(var):
    return "".join(f"\t\t\t{CH[c]['portrait']} = {{ {cv(var, CID[c])} }}\n" for c in CID)


imgs = [f"\t\tSOV_pres_leader_portrait = {{\n{portrait_list('SOV_pres_leader_char')}\t\t\t{BLANK} = yes\n\t\t}}\n"]
for L in LAYOUTS:
    for i in range(1, L[2] + 1):
        imgs.append(f"\t\tSOV_pres_L{L[0]}_s{i}_portrait = {{\n"
                    f"\t\t\t{BLANK} = {{ NOT = {{ AND = {{ {slot_shown(L, i)} }} }} }}\n"
                    f"{portrait_list(f'SOV_pres_seat_char^{i - 1}')}\t\t\t{UNKNOWN} = yes\n\t\t}}\n")
write("common/focus_inlay_windows/SOV_Stalin_presidium_inlay_window.txt", HDR + f"""SOV_Stalin_presidium_inlay = {{
	window_name = SOV_presidium_inlay_window
	internal = no
	visible = {{ has_country_flag = SOV_pres_initialized }}
	scripted_images = {{
{''.join(imgs)}	}}
}}
""")

# ============================================================ scripted effects
# HOI4 scripted effects take NO parameters: arguments are passed in temp variables.
VER = zlib.crc32(repr((CHARACTERS, MINISTRIES)).encode()) % 1000000
E = [HDR, """# ---------------------------------------------------------------------------
# HOW TO CALL (country scope, SOV). Arguments go in temp variables first:
#   pres_char = SOV_pres_char_id_<character>     pres_min = SOV_pres_min_id_<ministry>
#
#   set_temp_variable = { pres_min = SOV_pres_min_id_gosplan }
#   SOV_pres_add_seat = yes          # new empty seat at the end
#   SOV_pres_remove_seat = yes       # removes that seat, later seats move up
#   SOV_pres_vacate = yes            # empties that seat
#
#   set_temp_variable = { pres_char = SOV_pres_char_id_malenkov }
#   set_temp_variable = { pres_min = SOV_pres_min_id_gosplan }
#   SOV_pres_appoint = yes           # leaves his old seat automatically
#
#   set_temp_variable = { pres_char = SOV_pres_char_id_beria }
#   SOV_pres_dismiss = yes
#
#   SOV_pres_clear_seats = yes
#
# Plain variables, change them directly:
#   SOV_pres_<char>_faction (faction id)   SOV_pres_<char>_relation (-100..100)
#   SOV_pres_<char>_rank (2 full, 1 candidate, 0 none)
#   SOV_pres_leader_char = SOV_pres_char_id_<char>   SOV_pres_leader_title = SOV_pres_min_id_<post>
#
# DATA: seats are two parallel arrays, index 0 = first seat, count = SOV_pres_seat_min^num
#   SOV_pres_seat_min^i  ministry id     SOV_pres_seat_char^i  character id (0 = vacant)
# ---------------------------------------------------------------------------

"""]
E.append(f"SOV_pres_constants = {{\n\tset_variable = {{ SOV_pres_data_version = {VER} }}\n")
E += [f"\tset_variable = {{ SOV_pres_char_id_{c} = {i} }}\n" for c, i in CID.items()]
E += [f"\tset_variable = {{ SOV_pres_min_id_{m} = {i} }}\n" for m, i in MID.items()]
E.append("}\n\n")

E.append("SOV_pres_init = {\n\tset_country_flag = SOV_pres_initialized\n\tSOV_pres_constants = yes\n")
for c in CHARACTERS:
    k = c["key"]
    E.append(f"\tset_variable = {{ SOV_pres_{k}_faction = {FID[c['faction']]} }} set_variable = {{ SOV_pres_{k}_relation = {c['relation']} }} set_variable = {{ SOV_pres_{k}_rank = {c.get('politburo', 0)} }}\n")
E.append(f"\tset_variable = {{ SOV_pres_leader_char = {CID[START_LEADER[0]]} }} # {START_LEADER[0]}\n"
         f"\tset_variable = {{ SOV_pres_leader_title = {MID[START_LEADER[1]]} }} # {START_LEADER[1]}\n"
         "\tclear_array = SOV_pres_seat_min\n\tclear_array = SOV_pres_seat_char\n")
for m, h in START_SEATS:
    E.append(f"\tadd_to_array = {{ SOV_pres_seat_min = {MID[m]} }} add_to_array = {{ SOV_pres_seat_char = {CID[h] if h else 0} }} # {m}: {h or 'vacant'}\n")
E.append("}\n\n")

E.append(f"""SOV_pres_add_seat = {{ # pres_min
	if = {{
		limit = {{ check_variable = {{ SOV_pres_seat_min^num < {MAX_SEATS} }} }}
		add_to_array = {{ SOV_pres_seat_min = pres_min }}
		add_to_array = {{ SOV_pres_seat_char = 0 }}
	}}
}}

SOV_pres_remove_seat = {{ # pres_min
	set_temp_variable = {{ pres_idx = -1 }}
	for_each_loop = {{
		array = SOV_pres_seat_min
		if = {{
			limit = {{ check_variable = {{ v = pres_min }} }}
			set_temp_variable = {{ pres_idx = i }}
			set_temp_variable = {{ break = 1 }}
		}}
	}}
	if = {{
		limit = {{ check_variable = {{ pres_idx > -1 }} }}
		remove_from_array = {{ array = SOV_pres_seat_min index = pres_idx }}
		remove_from_array = {{ array = SOV_pres_seat_char index = pres_idx }}
	}}
}}

SOV_pres_clear_seats = {{
	clear_array = SOV_pres_seat_min
	clear_array = SOV_pres_seat_char
}}

SOV_pres_dismiss = {{ # pres_char
	for_each_loop = {{
		array = SOV_pres_seat_char
		if = {{
			limit = {{ check_variable = {{ v = pres_char }} }}
			set_variable = {{ SOV_pres_seat_char^i = 0 }}
		}}
	}}
}}

SOV_pres_appoint = {{ # pres_char, pres_min
	SOV_pres_dismiss = yes
	for_each_loop = {{
		array = SOV_pres_seat_min
		if = {{
			limit = {{ check_variable = {{ v = pres_min }} }}
			set_variable = {{ SOV_pres_seat_char^i = pres_char }}
		}}
	}}
}}

SOV_pres_vacate = {{ # pres_min
	for_each_loop = {{
		array = SOV_pres_seat_min
		if = {{
			limit = {{ check_variable = {{ v = pres_min }} }}
			set_variable = {{ SOV_pres_seat_char^i = 0 }}
		}}
	}}
}}
""")
write("common/scripted_effects/SOV_Stalin_presidium_effects.txt", "".join(E))

# ============================================================ on_actions
write("common/on_actions/SOV_Stalin_presidium_on_actions.txt", HDR + f"""on_actions = {{
	on_startup = {{
		effect = {{
			SOV = {{ if = {{ limit = {{ NOT = {{ has_country_flag = SOV_pres_initialized }} }} SOV_pres_init = yes }} }}
		}}
	}}
	on_monthly_SOV = {{
		effect = {{
			if = {{ limit = {{ NOT = {{ has_country_flag = SOV_pres_initialized }} }} SOV_pres_init = yes }}
			else_if = {{ limit = {{ NOT = {{ check_variable = {{ SOV_pres_data_version = {VER} }} }} }} SOV_pres_constants = yes }}
		}}
	}}
}}
""")

# ============================================================ scripted localisation
def defined(name, branches, default="SOV_pres_empty"):
    b = "".join(f"\ttext = {{ trigger = {{ {trig} }} localization_key = {key} }}\n" for trig, key in branches)
    return f"defined_text = {{\n\tname = {name}\n{b}\ttext = {{ localization_key = {default} }}\n}}\n"


SL = [HDR]
for c in CHARACTERS:
    ck = c["key"]
    SL.append(defined(f"SOV_pres_{ck}_faction_name",
                      [(cv(f"SOV_pres_{ck}_faction", FID[f]), f"SOV_pres_faction_{f}") for f, _ in FACTIONS], "SOV_pres_faction_none"))
    SL.append(defined(f"SOV_pres_{ck}_rank_name", [(cv(f"SOV_pres_{ck}_rank", 2), "SOV_pres_rank_full"),
                      (cv(f"SOV_pres_{ck}_rank", 1), "SOV_pres_rank_candidate")], "SOV_pres_rank_none"))
    SL.append(defined(f"SOV_pres_{ck}_ranked_name", [(cv(f"SOV_pres_{ck}_rank", 2), f"SOV_pres_char_{ck}_r2"),
                      (cv(f"SOV_pres_{ck}_rank", 1), f"SOV_pres_char_{ck}_r1")], f"SOV_pres_char_{ck}_r0"))
char_br = lambda var, suffix: [(cv(var, CID[c]), f"SOV_pres_char_{c}{suffix}") for c in CID]
min_br = lambda var: [(cv(var, MID[m]), f"SOV_pres_min_{m}") for m in MID]
SL.append(defined("SOV_pres_title_text", [("has_country_flag = SOV_pres_presidium_name", "SOV_pres_title")], "SOV_pres_title_politburo"))
SL.append(defined("SOV_pres_leader_name", char_br("SOV_pres_leader_char", "")))
SL.append(defined("SOV_pres_leader_title", min_br("SOV_pres_leader_title")))
SL.append(defined("SOV_pres_leader_tt", char_br("SOV_pres_leader_char", "_leader_tt")))
for i in SLOTS:
    SL.append(defined(f"SOV_pres_s{i}_name", char_br(f"SOV_pres_seat_char^{i - 1}", "_ranked_ui"), "SOV_pres_vacant"))
    SL.append(defined(f"SOV_pres_s{i}_title", min_br(f"SOV_pres_seat_min^{i - 1}")))
    SL.append(defined(f"SOV_pres_s{i}_faction", char_br(f"SOV_pres_seat_char^{i - 1}", "_faction_ui")))
    SL.append(defined(f"SOV_pres_s{i}_tt", char_br(f"SOV_pres_seat_char^{i - 1}", "_tt"), "SOV_pres_vacant_tt"))
for L in LAYOUTS:
    for i in range(1, L[2] + 1):
        for part in ("name", "title", "faction", "tt"):
            SL.append(defined(f"SOV_pres_L{L[0]}_s{i}_{part}", [(slot_shown(L, i), f"SOV_pres_s{i}_{part}_ui")]))
write("common/scripted_localisation/SOV_Stalin_presidium_scripted_loc.txt", "\n".join(SL))

# ============================================================ localisation
LEGEND = ("§YHow to read the panel§!\\nNames: §Ygold§! full member, white candidate member, §ggrey§! not a member of the Politburo.\\n"
          "Factions: " + ", ".join(n for _, n in FACTIONS) + ".\\nHover over a portrait for his faction, standing and traits.")
Lc = ['l_english:\n', ' SOV_pres_title:0 "Presidium of the Central Committee and Government"\n', ' SOV_pres_title_politburo:0 "Politburo of the Central Committee and Government"\n',
      ' SOV_pres_rank_full:0 "§YFull member§!"\n', ' SOV_pres_rank_candidate:0 "Candidate member"\n', ' SOV_pres_rank_none:0 "§gNot a member§!"\n',
      ' SOV_pres_vacant:0 "§gVacant§!"\n', ' SOV_pres_empty:0 ""\n',
      ' SOV_pres_vacant_tt:0 "This seat is vacant."\n', ' SOV_pres_faction_none:0 "§gUnaligned§!"\n']
Lc += [f' SOV_pres_faction_{f}:0 "{name}"\n' for f, name in FACTIONS]
Lc += [f' SOV_pres_min_{m}:0 "{title}"\n' for m, title in MINISTRIES]
for i in SLOTS:
    Lc += [f' SOV_pres_s{i}_{p}_ui:0 "[SOV_pres_s{i}_{p}]"\n' for p in ("name", "title", "faction", "tt")]
for c in CHARACTERS:
    ck = c["key"]
    head = (f"§Y{c['name']}§!\\n{c['bio']}\\n\\nFaction: [SOV_pres_{ck}_faction_name]\\n"
            f"Politburo: [SOV_pres_{ck}_rank_name]\\nRelationship with the leader: [?SOV_pres_{ck}_relation|+0]")
    Lc += [f' SOV_pres_char_{ck}:0 "{c["name"]}"\n',
           f' SOV_pres_char_{ck}_ranked_ui:0 "[SOV_pres_{ck}_ranked_name]"\n',
           f' SOV_pres_char_{ck}_r2:0 "§Y{c["name"]}§!"\n',
           f' SOV_pres_char_{ck}_r1:0 "{c["name"]}"\n',
           f' SOV_pres_char_{ck}_r0:0 "§g{c["name"]}§!"\n',
           f' SOV_pres_char_{ck}_faction_ui:0 "[SOV_pres_{ck}_faction_name]"\n',
           f' SOV_pres_char_{ck}_leader_tt:0 "§Y{c["name"]}§!\\n{c["bio"]}\\n\\n' + LEGEND + '"\n']
    traits = "".join(f"\\n§Y{TRAITS[t][0]}§!: {TRAITS[t][1]}" for t in c["traits"])
    Lc.append(f' SOV_pres_char_{ck}_tt:0 "{head}' + (f"\\n{traits}" if traits else "") + '"\n')
# tooltips for the panel hooks in SOV_Stalin.txt (Mingrelian affair, 19th Congress, Beria's arrest)
Lc += [' SOV_pres_hook_mingrelian_tt:0 "§YLavrentiy Beria§!: relationship with the leader §R-25§!"\n',
       ' SOV_pres_hook_congress_tt:0 "The Politburo is renamed the §YPresidium of the Central Committee§!.\\n§YVyacheslav Molotov§!: relationship with the leader §R-30§!\\n§YAnastas Mikoyan§!: relationship with the leader §R-30§!"\n',
       ' SOV_pres_hook_beria_tt:0 "§YLavrentiy Beria§! loses his seat."\n']
write("localisation/english/SOV_Stalin_presidium_l_english.yml", "".join(Lc), bom=True)

# ============================================================ focus tree position
tree = MOD / "common/national_focus/SOV_Stalin.txt"
if tree.exists():
    s = tree.read_bytes().decode("utf-8")
    s2 = re.sub(r"(id = SOV_Stalin_presidium_inlay\s*\r?\n\s*position = \{ x = )\d+( y = )\d+",
                rf"\g<1>{INLAY_POSITION[0]}\g<2>{INLAY_POSITION[1]}", s)
    if s2 != s:
        tree.write_bytes(s2.encode("utf-8"))
        print("updated inlay position in SOV_Stalin.txt")

for L in LAYOUTS:
    print(f"layout {L[0]}: {L[1] + 1}-{L[2]} seats -> {L[3]} cols x {L[4]} rows, scale {L[5]:.2f}")
print(f"panel {W}x{H}")
