NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_AFTER = {0, 9, 20} -- After this amount of VP the map icon becomes bigger dot.
NDefines_Graphics.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048
NDefines_Graphics.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 2048
NDefines_Graphics.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 512
NDefines_Graphics.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10
NDefines_Graphics.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 8196
NDefines_Graphics.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41
NDefines_Graphics.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 24000
NDefines_Graphics.NGraphics.MAX_NUMBER_OF_TEXTURES = 25000
NDefines_Graphics.NGraphics.MINIMUM_PROVINCE_SIZE_IN_PIXELS = 3
NDefines_Graphics.NGraphics.POLITICAL_GRID_SMALL_BOX_LIMIT = 100             	-- Don't even touch this.
NDefines_Graphics.NGraphics.FRIEND_COLOR  = {1.0, 1.0, 1.0}
NDefines_Graphics.NGraphics.ENEMY_COLOR   = {1.0, 1.0, 1.0}
NDefines_Graphics.NGraphics.NEUTRAL_COLOR = {1.0, 1.0, 1.0}
NDefines_Graphics.NGraphics.BLOOM_SCALE = 2.9
NDefines_Graphics.NGraphics.COUNTRY_COLOR_HUE_MODIFIER = 0.0 -- 0.0
NDefines_Graphics.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 0.7 -- 0.6
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_COUNTRY_CENTER_THICKNESS = 1.0 -- 2.0
NDefines_Graphics.NGraphics.COUNTRY_COLOR_BRIGHTNESS_MODIFIER = 0.8 -- 0.8
NDefines_Graphics.NGraphics.BORDER_WIDTH = 1.75
NDefines_Graphics.NGraphics.GRADIENT_BORDERS_OPTIMIZATION_RANGE = 25
NDefines_Graphics.NMapIcons.STATES_PRIORITY_VICTORY_POINTS = 4
NDefines_Graphics.NFrontend.CAMERA_MAX_HEIGHT = 3500.0
NDefines_Graphics.NFrontend.CAMERA_MIN_HEIGHT = 35.0
NDefines_Graphics.NSound.BATTLE_SOUND_MIN_UNIT_COUNT = 4
NDefines_Graphics.NInterface.SLOW_INTERFACE_THRESHOLD = 25000
NDefines_Graphics.NAirGfx.AIRPLANES_ANIMATION_GLOBAL_SPEED_PER_GAMESPEED = { 0.15, 0.15, 0.15, 0.15, 0.15, 0.15 } 
NDefines_Graphics.NAirGfx.FIGHTER_DIVISION_FACTOR = 10.0
NDefines_Graphics.NAirGfx.TRANSPORT_DIVISION_FACTOR = 10.0
NDefines_Graphics.NAirGfx.TRAINING_MISSION_DIVISION_FACTOR = 10.0
NDefines_Graphics.NAirGfx.MAX_MISSILE_BOMBING_SCENARIOS = 15.0
NDefines_Graphics.NAirGfx.MAX_PATROL_SCENARIOS = 2.0
NDefines_Graphics.NAirGfx.MAX_BOMBING_SCENARIOS = 3.0
NDefines_Graphics.NAirGfx.MAX_DOGFIGHTS_SCENARIOS = 3.0
NDefines_Graphics.NAirGfx.MAX_TRANSPORT_SCENARIOS = 3.0
NDefines_Graphics.NAirGfx.MAX_TRAINING_SCENARIOS = 2.0